export const surpriseMePrompts = [
  'A cozy cabin in the middle of a mystical forest, surrounded by fireflies',
  'A futuristic cityscape with floating gardens and neon-lit skyscrapers',
  'An enchanted library where books come to life as you read them',
  'A steampunk submarine exploring the depths of an alien ocean',
  'A magical portal opening in the middle of a bustling marketplace',
  'A surreal underwater world with bioluminescent creatures',
  'A majestic dragon sleeping peacefully atop a mountain of gold',
  'A whimsical carousel populated with mythical creatures instead of animals',
  'A haunted mansion with flickering candles and creaking floorboards',
  'A secret garden hidden behind a waterfall, filled with exotic flowers',
  'An ancient temple overgrown with vines and surrounded by mist',
  'A floating island in the sky, inhabited by winged cats',
  'A time-traveling adventurer exploring ancient Egypt',
  'A parallel universe where gravity works differently',
  'A mechanical forest where trees are made of gears and cogs',
  'A celestial ballet performed by planets and stars',
  'A sentient cityscape where buildings have faces and personalities',
  'A futuristic sushi restaurant run entirely by robots',
  'A wizard\'s workshop filled with bubbling potions and magical artifacts',
  'A cyberpunk street scene with holographic billboards and flying cars',
  'A mythical phoenix rising from the ashes of an ancient civilization',
  'A labyrinthine maze with shifting walls and hidden treasures',
  'A magical ice castle shimmering under the northern lights',
  'A carnival at the edge of a black hole, with gravity-defying attractions',
  'A futuristic amusement park on Mars, complete with zero-gravity rides',
  'A whimsical tea party hosted by talking animals in an enchanted forest',
  'A retro-futuristic space station orbiting a distant planet',
  'A cosmic ocean filled with constellations instead of fish',
  'A majestic unicorn grazing in a field of rainbow-colored flowers',
  'A surreal desert landscape with floating islands of water',
  'A haunted shipwreck inhabited by ghostly pirates',
  'A time-traveling train journeying through different eras of history',
  'A mystical fairy tale castle guarded by mythical beasts',
  'A steampunk city powered by giant clockwork mechanisms',
  'A magical marketplace where potions and spells are bought and sold',
  'A futuristic laboratory where scientists create artificial life forms',
  'A mythical forest inhabited by talking animals and wise old trees',
  'A space colony on a distant planet, bustling with alien species',
  'A celestial garden where planets bloom like flowers',
  'A hidden underwater city illuminated by glowing jellyfish',
  'A cybernetic jungle where plants are intertwined with technology',
  'A fantasy world where clouds are made of cotton candy',
  'A futuristic sports arena where humans compete against robots',
  'A cosmic library containing books written by extraterrestrial authors',
  'A magical carnival where illusions come to life',
  'A dystopian cityscape under the rule of sentient AI',
  'A post-apocalyptic wasteland reclaimed by nature',
  'A mythical creature sanctuary hidden in the heart of a volcano',
  'A steampunk circus with mechanical animals and acrobats',
  'A futuristic metropolis where skyscrapers touch the clouds'
];